# Generated by Django 4.1.2 on 2022-10-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="text",
            field=models.TextField(default="", verbose_name=""),
        ),
    ]
